// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMWfpLBbyCVV5X5i1lKEjonZ7AoTlHOm4',
    appId: '1:258391559422:web:4b31dc627d209f1e3f29af',
    messagingSenderId: '258391559422',
    projectId: 'my-fire-sw',
    authDomain: 'my-fire-sw.firebaseapp.com',
    storageBucket: 'my-fire-sw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sA4RHxdj25PqOMPtXpxLrllnr8G5VOo',
    appId: '1:258391559422:android:a7878663b3814bb23f29af',
    messagingSenderId: '258391559422',
    projectId: 'my-fire-sw',
    storageBucket: 'my-fire-sw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnzpibFQUx3dKcHb5jHSQQXJA1XzD60g',
    appId: '1:258391559422:ios:52e0a962081a5c2d3f29af',
    messagingSenderId: '258391559422',
    projectId: 'my-fire-sw',
    storageBucket: 'my-fire-sw.appspot.com',
    iosBundleId: 'com.fireflutter.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPnzpibFQUx3dKcHb5jHSQQXJA1XzD60g',
    appId: '1:258391559422:ios:52e0a962081a5c2d3f29af',
    messagingSenderId: '258391559422',
    projectId: 'my-fire-sw',
    storageBucket: 'my-fire-sw.appspot.com',
    iosBundleId: 'com.fireflutter.flutterFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMWfpLBbyCVV5X5i1lKEjonZ7AoTlHOm4',
    appId: '1:258391559422:web:51b38ccdb780fc303f29af',
    messagingSenderId: '258391559422',
    projectId: 'my-fire-sw',
    authDomain: 'my-fire-sw.firebaseapp.com',
    storageBucket: 'my-fire-sw.appspot.com',
  );
}
